### ISSUE TITLE
can't find API

### ISSUE THREAD

**Issue by camaz** [acd/infinitive#11]
Loving Infinitive, but I can't seem to GET any of the API except /api/zone/1/config.
../heatpump and ../airhandler produce a 404?
Any thoughts? Any way I can help contribute (logs or similar)?
Thanks!

**Comment by Will1604** [comment]
Which version are you running?
The code on acd/infinitive master should have the api at _host:port_/api/zone/1/heatpump etc.

For my branch - will1604/master they're at  _host:port_/api/heatpump etc. As the heat pump and furnace/fan coil are not specific to a zone I was proposing the zone out of the URL.

**Comment by camaz** [comment]
built from source, works great!
