### ISSUE TITLE
Link to Cocoontech broke in README

### ISSUE THREAD

**Issue by ehwest** [acd/infinitive#6]
in README
Link to 
Cocoontech's Carrier Infinity Thread
Broke

**Comment by Will1604** [comment]
Works for me.
http://cocoontech.com/forums/topic/11372-carrier-infinity/

**Comment by ehwest** [comment]
Very sorry....Buried in the README there is this.  These links go nowhere.
OK, try this.

www.hvac-talk.com/vbb/attachment.php?attachmentid=3061&d=1185394256 

http://www.xpedio.ca...11-20156-25.pdf

**Comment by acd** [comment]
Not sure what you're talking about; those links are not included in any of the Infinitive documentation.  I am closing this issue.

**Comment by Will1604** [comment]
Those links were in a post on the Cocoontech forum. Looks like the poster was posting documents for the SAM. I've found this previously. I think it's the same document.
http://gpsinformation.info/joe/carrier/InfinityThermostatSpecifications.pdf
Describes the protocols a home automation system would use to interface with the SAM using RS-232.

**Comment by ehwest** [comment]
Thats it, Will1604 Thanks!
